package dev.squidutils.fusion.hud;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.resources.Identifier;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * Shard icons, drawn from a single texture atlas.
 *
 * <p>Originally each shard was its own texture. Minecraft loads standalone
 * textures on demand, and enough of them failed to resolve that rows past the
 * first handful drew as the magenta missing-texture check - consistently, once
 * a table was tall enough. One atlas removes the whole problem: it loads once,
 * cannot half-load, and collapses hundreds of texture binds into one.
 *
 * <p>The atlas and its index are generated by {@code mod/tools/BuildAtlas.java}
 * from the icons the wiki fetch script downloads.
 */
public final class ShardIcons {

    private static final Identifier ATLAS =
            Identifier.fromNamespaceAndPath("squidutils", "textures/shard_atlas.png");

    private static final Map<String, Integer> INDEX = new HashMap<>();
    private static int cell = 32;
    private static int cols = 18;
    private static int width = 576;
    private static int height = 576;

    private ShardIcons() {}

    public static void load(InputStream in) {
        INDEX.clear();
        if (in == null) return;
        try (var reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            cell = root.get("cell").getAsInt();
            cols = root.get("cols").getAsInt();
            width = root.get("width").getAsInt();
            height = root.get("height").getAsInt();
            var names = root.getAsJsonArray("names");
            for (int i = 0; i < names.size(); i++) {
                INDEX.put(names.get(i).getAsString(), i);
            }
        } catch (Exception ignored) {
            // No atlas index means no icons; the rarity tile takes over.
            INDEX.clear();
        }
    }

    public static int count() {
        return INDEX.size();
    }

    public static Identifier atlas() { return ATLAS; }
    public static int cell() { return cell; }
    public static int atlasWidth() { return width; }
    public static int atlasHeight() { return height; }

    /** Cell index for a bazaar tag such as SHARD_HIDEONRING, or -1 if absent. */
    public static int indexOf(String tag) {
        if (tag == null || INDEX.isEmpty()) return -1;
        String key = tag.toLowerCase(Locale.ROOT);
        if (key.startsWith("shard_")) key = key.substring(6);
        Integer i = INDEX.get(key);
        return i == null ? -1 : i;
    }

    public static int cellX(int index) { return (index % cols) * cell; }

    public static int cellY(int index) { return (index / cols) * cell; }
}
